# Auto compile, test and deploy Java project with Maven CI
name: MAVEN - Compile, test and deploy maven project

on:
  push:
    branches: [ master ]
# pull_request:
#   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project revision
      uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
#   - name: Build with Maven
#     run: mvn -B package --file pom.xml
    - name: Prepare the authentication configuration
      env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp .github/config/settings.xml ~/.m2/
        sed -i "s/{UNIT}/sample/g; s/{USER}/feony/g; s/{PASS}/$TOKEN/g" ~/.m2/settings.xml
    - name: Deploy with Maven
      run: mvn deploy
